spring.datasource.url=mysql://bef8137e24e012:f5800230@us-cdbr-east-03.cleardb.com/heroku_199e051f1cb4451?reconnect=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
